<?php
$urlBase = OntoWiki::getInstance()->getUrlBase();
?>
<div class="standard-report-module">
    <div id="report-accordion" class="report-list">
    <?php foreach ($this->queries as $id => $query): ?>
        <h3 class="report-title"><?php echo $query->label ?></h3>
        <form class="" method="get" action="<?php echo ($urlBase . 'reports/report')?>">
            <span class="actions">
                <input type="hidden" name="queryID" value="<?php echo $id ?>">
                <button id="showCSVButton" class="button" type="submit" name="csv_format" value="1">CSV</button>
                <button id="showHTMLButton" class="button" type="submit" name="html_format" value="1">Show</button>
            </span>
            <p class="report-description"><?php echo $query->description ?></p>

            <?php if ($query->parameter): ?>
            <table class="parameter-table">
            <?php foreach ($query->parameter as $param_id => $parameter): ?>
                <tr>
                    <td class="label">
                        <label><?php echo $parameter->label ?></label>
                    </td>
                    <td>
                    <?php if (!$parameter->type): ?>
                        <input class="text" type="text" name="parameter[<?php echo $param_id ?>]">
                    <?php elseif ($parameter->type === 'http://www.w3.org/2001/XMLSchema#integer'): ?>
                        <input class="text" type="number" name="parameter[<?php echo $param_id ?>]">
                    <?php else: ?>
                        <input class="typeahead" type="text" name="parameter[<?php echo $param_id ?>]">
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </table>
            <?php endif; ?>
        </form>
    <?php endforeach ?>
    </div>
</div>