<?php
$urlBase = OntoWiki::getInstance()->getUrlBase();
$trans = OntoWiki::getInstance()->translate;
?>

<div class="standard-report-module">
    <?php if ($this->has('error')): ?>
        <fieldset>
            <div class="messagebox error"><?php echo $this->error ?></div>
        </fieldset>
    <?php endif; ?>

    <?php if ($this->has('no_results')): ?>
        <div class="messagebox"><?php echo $trans->_('No results for this query')?>! <a href="<?php echo ($urlBase . 'reports/list')?>"><?php echo $trans->_('Back')?></a></div>
    <?php endif; ?>

    <?php if (!$this->has('no_results')): ?>
        <h3><?php echo sprintf($trans->_('Result for query "%1$s"'), $this->query->label)?> <a href="<?php echo ($urlBase . 'reports/list')?>"><?php echo $trans->_('All Reports')?></a></h3>
        <?php if (count($this->data) >= $this->limit): ?>
            <div class="messagebox warning"><?php echo sprintf($trans->_('This report has been truncated to %1$s results! Please use the CSV option to get all results.'), $this->limit)?></div>
        <?php endif; ?>
        <fieldset>
            <?php if (is_array($this->data)): ?>
                <?php
                echo $this->partial(
                    'partials/resultset.phtml',
                    array(
                        'data' => $this->data,
                        'header' => $this->header,
                        'urlBase' => $urlBase
                    )
                );
                ?>
            <?php else: ?>
                <pre><?php echo $this->escape($this->data) ?></pre>
            <?php endif; ?>
        </fieldset>
    <?php endif; ?>
</div>