<div class="standard-report-module">
    <ul class="report-list">
    <?php foreach ($this->queries as $id => $query): ?>
        <li class="item">
            <form class="" method="get" action="/reports/report">
                <label class="report-title"><?php echo $query->label ?></label>
                <span class="actions">
                    <input type="hidden" name="queryID" value="<?php echo $id ?>">
                    <button id="showCSVButton" class="button" type="submit" name="csv_format" value="1">CSV</button>
                    <button id="showHTMLButton" class="button" type="submit" name="html_format" value="1">Show</button>
                </span>
                <p class="report-description"><?php echo $query->description ?></p>

                <?php if ($query->parameter): ?>
                <?php foreach ($query->parameter as $param_id => $parameter): ?>
                        <label>Parameter <?php echo $param_id ?></label>
                        <input type="text" name="parameter[<?php echo $param_id ?>]">
                <?php endforeach ?>
                <?php endif; ?>
            </form>
        </li>
    <?php endforeach ?>
    </ul>
</div>