<!--<script type="text/javascript" id="RDFauthorScript" src="--><?php //echo $this->libraryUrlBase ?><!--RDFauthor/src/rdfauthor.js"></script>-->

<div class="standard-report-module">
    <ul class="report-list">
    <?php foreach ($this->queries as $id => $query): ?>
        <li class="item">
            <form class="" method="get" action="/reports/report">
                <label class="report-title"><?php echo $query->label ?></label>
                <span class="actions">
                    <input type="hidden" name="queryID" value="<?php echo $id ?>">
                    <input type="hidden" name="format" value="text/csv">
                    <button id="showHTMLButton" class="button" type="submit">CSV</button>
                </span>
                <p class="report-description"><?php echo $query->description ?></p>

                <?php if ($query->parameter): ?>
                <?php foreach ($query->parameter as $param_id => $parameter): ?>
                        <label>Parameter <?php echo $param_id ?></label>
                        <input type="text" name="parameter[<?php echo $param_id ?>]">
                <?php endforeach ?>
                <?php endif; ?>
            </form>
        </li>
    <?php endforeach ?>
    </ul>
</div>