<?php
$translate = OntoWiki::getInstance()->translate;
?>
<br>
<?php echo($translate->translate("Values of property"))?>: <?php echo $this->propertyTitle ?><br><br>
<div class="literal-list-view-module">
    <ul>
        <?php foreach ($this->results as $result): ?>
            <li>
                    <label><?php echo $result['value'] ?></label>
                </li>
        <?php endforeach ?>

    </ul>
</div>