<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2006-2013, {@link http://aksw.org AKSW}
 * @license   http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * OntoWiki lastcomments module template
 *
 * @author     Sebastian Tramp <tramp@informatik.uni-leipzig.de>
 * @author     Natanael Arndt <arndtn@gmail.com>
 */
?>
<?php if ($this->has('infomessage')): ?>
    <p id="commentbox-noMessages"class="messagebox info"><?php echo $this->_($this->infomessage) ?></p>
<?php endif?>
    <div id="comment-list" style="max-height: 300px;">
        <?php if ($this->has('comments')): ?>
    <?php echo $this->comments; ?>
        <?php endif?>
    </div>
<?php if ($this->has('comments')): ?>
    <?php if ($this->has('more')): ?>
        <p class="messagebox info">There are more comments out there ...</p>
    <?php endif?>
<?php endif?>